all: simple-example bootstrap-example

simple-example:
	cd .. && elm make --warn examples/simple/Simple.elm --output=examples/simple/simple.js

bootstrap-example:
	cd .. && elm make --warn examples/bootstrap/Bootstrap.elm --output=examples/bootstrap/bootstrap.js
